### ISSUE TITLE
Swagger validation errors: additional properties - shape, documentation

### ISSUE THREAD

**Issue by mterrel** [APIs-guru/aws2openapi#6]
I get schema validation errors when trying to run the current version of this tool. Steps to reproduce are:
```
git clone <aws2openapi url>
git clone <openapi-directory url>
git clone <aws-sdk-js url>
cd aws2openapi
npm install
. processYaml.sh
```

Example error output from processing just one API:
```
node aws2openapi.js ../aws-sdk-js/apis/cloudformation-2010-05-15.normal.json ../openapi-directory/APIs/amazonaws.com -y
/home/mark/oss/aws-sdk-js/apis/cloudformation-2010-05-15.normal.json
  Has paginators
  Has examples version 1.0
  Has waiters version 2
{"serviceName":"cloudformation","versions":[],"preferred":"2010-05-15"}
/home/mark/oss/aws-sdk-js/apis/cloudformation-2010-05-15.normal.json
Failed validation (simple): /home/mark/oss/aws-sdk-js/apis/cloudformation-2010-05-15.normal.json
[ { field: 'data.definitions',
    message: 'referenced schema does not match' } ]
/home/mark/oss/aws-sdk-js/apis/cloudformation-2010-05-15.normal.json
{
  "details": [
    {
      "code": "ANY_OF_MISSING",
      "params": [],
      "message": "Data does not match any schemas from 'anyOf'",
      "path": [
        "definitions",
        "TransformsList",
        "items"
      ],
      "schemaId": "http://swagger.io/v2/schema.json#",
      "inner": [
        {
          "code": "OBJECT_ADDITIONAL_PROPERTIES",
          "params": [
            [
              "shape"
            ]
          ],
          "message": "Additional properties not allowed: shape",
          "path": [
            "definitions",
            "TransformsList",
            "items"
          ],
          "description": "A deterministic version of a JSON Schema object."
        },
        {
          "code": "INVALID_TYPE",
          "params": [
            "array",
            "object"
          ],
          "message": "Expected type array but found type object",
          "path": [
            "definitions",
            "TransformsList",
            "items"
          ]
        }
      ]
    }
  ],
  "name": "SyntaxError",
  "message": "Swagger schema validation failed. 
  Data does not match any schemas from 'anyOf' at #/definitions/TransformsList/items
    Additional properties not allowed: shape at #/definitions/TransformsList/items
    Expected type array but found type object at #/definitions/TransformsList/items
 
JSON_OBJECT_VALIDATION_FAILED",
  "stack": "SyntaxError: Swagger schema validation failed. 
  Data does not match any schemas from 'anyOf' at #/definitions/TransformsList/items
    Additional properties not allowed: shape at #/definitions/TransformsList/items
    Expected type array but found type object at #/definitions/TransformsList/items
 
JSON_OBJECT_VALIDATION_FAILED
    at validateSchema (/home/mark/oss/aws2openapi/node_modules/swagger-parser/lib/validators/schema.js:27:15)
    at /home/mark/oss/aws2openapi/node_modules/swagger-parser/lib/index.js:152:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)

z-schema validation error: JSON_OBJECT_VALIDATION_FAILED
    at ZSchema.getLastError (/home/mark/oss/aws2openapi/node_modules/z-schema/src/ZSchema.js:260:13)
    at validateSchema (/home/mark/oss/aws2openapi/node_modules/swagger-parser/lib/validators/schema.js:25:23)
    at /home/mark/oss/aws2openapi/node_modules/swagger-parser/lib/index.js:152:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)"
}
```

The generated yaml files are different than those currently in the openapi-directory repo. Here's an example of the diff:
```
+++ b/APIs/amazonaws.com/cloudformation/2010-05-15/swagger.yaml
@@ -1617,11 +1617,11 @@ definitions:
       - StackName
     properties:
       StackName:
-        $ref: '#/definitions/StackName'
-        description: The name or the unique stack ID that is associated with the stack.
+        shape: StackName
+        documentation: <p>The name or the unique stack ID that is associated with the stack.</p>
       ClientRequestToken:
```
Notice that "shape" should have transformed into a "$ref" and "documentation" into "description", but that did not happen.

**Comment by MikeRalphson** [comment]
Please try the latest version. Thanks for flagging up the issue.

**Comment by mterrel** [comment]
Thanks for the quick response, @MikeRalphson! I removed node_modules and did an npm install and can run the tool successfully now. However, I took a look at some of the diffs in the resulting specs and see some odd diffs like this one that appear to be an error:
```
+++ b/APIs/amazonaws.com/AWSMigrationHub/2017-05-31/swagger.yaml
@@ -1288,8 +1288,7 @@ definitions:
       DryRun:
         $ref: '#/definitions/DryRun'
         description: Optional boolean flag to indicate whether any effect shoul
d take place. Used to test if the caller has permission to make the call.
-  ErrorMessage:
-    type: string
+  '[object Object]': {}
   ApplicationId:
```

I also noticed that when I do the npm install, it significantly modifies the committed package-lock.json. It doesn't seem to have any other effect besides updating to more recent package versions, but I thought that was particularly odd given what package-lock is supposed to do... Not sure if it warrants a closer look or not.

**Comment by mterrel** [comment]
And for the package-lock thing, I'd forgotten that NPM broke package-lock a while back. It doesn't "lock" to anything. (We've mostly been using yarn recently because of the many bone-headed things the NPM team has done like this. And it's **so** much faster for large projects.) See https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json for a pretty good explanation.

The short answer is: I should use `npm ci` instead of `npm install` now that there's a package-lock file. That command does **not** update packages.

Now that still doesn't explain why you and I get different results using `npm install`... I'm running NPM 6.4.1 on Node 10 on Amazon Linux:
```
CORP\mark@a-1ltyzh42bbrmy:~/oss/aws2openapi$ git show --oneline | head -1
ba715f3 fix [Object object], refs #8
CORP\mark@a-1ltyzh42bbrmy:~/oss/aws2openapi$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
CORP\mark@a-1ltyzh42bbrmy:~/oss/aws2openapi$ node --version
v10.11.0
CORP\mark@a-1ltyzh42bbrmy:~/oss/aws2openapi$ npm --version
6.4.1
CORP\mark@a-1ltyzh42bbrmy:~/oss/aws2openapi$ uname -a
Linux a-1ltyzh42bbrmy 4.14.77-86.82.amzn2.x86_64 #1 SMP Mon Dec 3 19:40:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
CORP\mark@a-1ltyzh42bbrmy:~/oss/aws2openapi$ rm -rf node_modules
CORP\mark@a-1ltyzh42bbrmy:~/oss/aws2openapi$ npm install
added 86 packages from 44 contributors and audited 104 packages in 2.899s
found 0 vulnerabilities

CORP\mark@a-1ltyzh42bbrmy:~/oss/aws2openapi$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```
And the resulting diffs of package-lock are huge. It updates everything to the latest versions allowed by package.json. For example, it updates yargs from 11.0.0 to 12.0.5. Now why it doesn't do that for you...who knows? Anyway, I'm not worried about it, so no action needed from my perspective.

Thanks again!

**Comment by MikeRalphson** [comment]
Fix applied for `undefined` appearing as a key in `definitions`. Thanks again for your eagle eyes! Unsure about the `npm i` differences though...

**Comment by MikeRalphson** [comment]
I see you're in Denver - I should be over in May for Gluecon.

**Comment by mterrel** [comment]
Thanks for the fix, Mike. Looks great.
We'll likely be at Gluecon as well. I sent you a LinkedIn request to keep in touch.
